syntax = "proto3";

message AgentReply {
    uint32 code = 1;
    string details = 2;
}

message NodeSelector {
    repeated string black_list = 1;
    repeated string white_list = 2;
}

message NvmeTrConf {
    string tr_type = 1;
    string adr_fam = 2;
    string tr_addr = 3;
    string tr_svc_id = 4;
}

message QosRatio {
    bool strict = 1;
    uint64 bytes_per_iops = 2;
    uint64 bytes_per_bps = 3;
}

message DmCloneConf {
    // region_size_in_byte = region_block_cnt * DmPoolConf.data_block_size
    uint64 region_block_cnt = 1;
	uint32 hydration_threshold  = 2;
	uint32 hydration_batch_size = 3;
}

message DmPoolConf {
    uint64 data_block_size = 1;
    uint32 low_water_mark_pct = 2;
}

message RedundNone {}

message RedundMdRaid1 {
    // chunk_size_in_byte = bitmap_chunk_block_cnt * DmPoolConf.data_block_size
    uint64 bitmap_chunk_block_cnt = 1;
}

message RedundConf {
   oneof RedunKind {
       RedundNone redund_none = 1;
	   RedundMdRaid1 redund_md_raid1 = 2;
   }
}

// Just a placeholder
message BdevFeatureNone {}

message BdevFeature {
    oneof BdevFeatureKind {
	    BdevFeatureNone bdev_feature_none = 1;
	}
}

message DmRaid0Conf {
    uint64 stripe_size = 1;
}

message BdevConf {
    DmPoolConf dm_pool_conf = 1;
    DmRaid0Conf dm_raid0_conf = 2;
	RedundConf redund_conf = 3;
	repeated BdevFeature bdev_feature_list = 4;
}

message NodeState {
    uint64 set_epoch = 1;
    uint64 clear_epoch = 2;
}

message SidePointer {
    uint64 sp_id = 1;
    uint64 leg_id = 2;
    uint64 side_id = 3;
}

message CntlrPointer {
    uint64 sp_id = 1;
    uint64 cntlr_id = 2;
}

message Side {
    uint64 side_id = 1;
    string addr_port = 2;
	NvmeTrConf nvme_tr_conf = 3;
    uint32 cntlid_slot = 4;
}

message Leg {
    uint64 leg_id = 1;
    uint32 leg_idx = 2;
    repeated Side side_list = 3;
}

message Group {
    uint64 grp_id = 1;
    uint64 ext_cnt = 2;
    uint64 meta_blocks = 3;
    uint64 data_blocks = 4;
    repeated Leg leg_list = 5;
    repeated Leg spare_leg_list = 6;
}

message Namespace {
    uint64 ns_id = 1;
    uint32 ns_idx = 2;
    uint64 td_id = 3;
    uint64 ag_id = 4;
    string dev_uuid = 5;
    string dev_nguid = 6;
    bool suspended = 7;
}

enum SpLevel {
    // all dm/md devices are readable/writable
    SP_LEVEL_READ_WRITE = 0;
    // all thin device are readonly
    // all side are readonly
    // all hydration of clones/migrations are disabled
    SP_LEVEL_READ_ONLY = 1;
    // include all things in SP_LEVEL_READ_ONLY
    // and doesn't create the dm-clone devices for migrations
    SP_LEVEL_NO_MIGRATION = 2;
    // include all things in SP_LEVEL_NO_MIGRRATION
    // and doesn't create the dm-clone devices for clones
    SP_LEVEL_NO_CLONE = 3;
    // include all things in SP_LEVEL_NO_CLONE
    // and doesn't create all dm-thinpool devices
    SP_LEVEL_NO_THINPOOL = 4;
    // include all things in SP_LEVEL_NO_THINPOOL
    // and doesn't create all raid 1/5/6 devices
    SP_LEVEL_NO_REDUND = 5;
}

enum ResStatus {
    // UNKNOWN means can't get response from dn/cn
    RES_STATUS_UNKNOWN = 0;
    // MISSING means dn/cn doesn't create it
    RES_STATUS_MISSING = 1;
    // ERROR means dn/cn tried to create it but failed
    RES_STATUS_ERROR = 2;
    // OK means OK
    RES_STATUS_OK = 3;
}

message ResInfo {
    string res_name = 1;
    ResStatus status = 2;
    string details = 3;
    uint64 epoch = 4;
}

message LiveInfo {
    uint64 revision = 1;
    uint32 format = 2;
    repeated ResInfo res_info = 3;
}

message DnBinConf {
    uint64 extent_size = 1;
    uint32 bin0_shift = 2;
    uint32 bin1_shift = 3;
    uint32 bin2_shift = 4;
    uint32 bin3_shift = 5;
}

message AllocConf {
    uint32 dn_batch_size = 1;
    uint32 cn_batch_size = 2;
}

// {dnv_prefix} cluster_conf {cluster_name}
message ClusterConf {
    QosRatio qos_ratio = 1;
    BdevConf bdev_conf = 2;
    DnBinConf dn_bin_conf = 3;
    AllocConf alloc_conf = 4;
}

// {dnv_prefix} dn_global {cluster_id}
message DnGlobal {
    uint64 next_id = 1;
    repeated uint32 shard_bucket = 2;
}

// {dnv_prefix} cn_global {cluster_id}
message CnGlobal {
    uint64 next_id = 1;
    repeated uint32 shard_bucket = 2;
}

// {dnv_prefix} sp_global {cluster_id}
message SpGlobal {
    uint64 next_id = 1;
    repeated uint32 shard_bucket = 2;
}

// {dnv_prefix} dn_rev {shard_code} {cluster_id} {addr_port}
message DnRev {
    uint64 revision = 1;
}

// {dnv_prefix} cn_rev {shard_code} {cluster_id} {addr_port}
message CnRev {
    uint64 revision = 1;
}

// {dnv_prefix} sp_rev {shard_code} {cluster_id} {sp_name}
message SpRev {
    uint64 revision = 1;
}

// {dnv_prefix} dn_conf {cluster_id} {addr_port}
message DnConf {
    uint64 dn_id = 1;
    uint32 shard_code = 2;
    repeated NodeState state_list = 3;
    NvmeTrConf nvme_tr_conf = 4;
    repeated SidePointer side_ptr_list = 5;
    uint64 total_ext_cnt = 6;
    uint64 free_ext_cnt = 7;
}

// {dnv_prefix} cn_conf {cluster_id} {addr_port}
message CnConf {
    uint64 cn_id = 1;
    uint32 shard_code = 2;
    repeated NodeState state_list = 3;
    NvmeTrConf nvme_tr_conf = 4;
    repeated CntlrPointer cntlr_ptr_list = 5;
    uint64 total_ext_cnt = 6;
    uint64 free_ext_cnt = 7;
}

// {dnv_prefix} dn_capacity {cluster_id} {bin_idx} {free_ext_cnt} {addr_port}
message DnCapacity {
    string location = 1;
}

// {dnv_prefix} cn_capacity {cluster_id} {free_ext_cnt} {addr_port}
message CnCapacity {
    string location = 1;
}

// {dnv_prefix} cdc {cluster_id} {shard_code} {sp_id} {ss_id}
message CdcEntry {
    string nqn = 1;
    repeated NvmeTrConf nvme_tr_conf_list = 2;
    repeated string allowed_hosts = 3;
}

// {dnv_prefix} sp_conf {cluster_id} {sp_name}
message SpConf {
    uint64 sp_id = 1;
    uint32 shard_code = 2;
    uint64 next_id = 3;
    uint32 next_dev_id = 4;
    BdevConf bdev_conf = 5;
	repeated uint32 cntlid_slot_list = 7;
	SpLevel sp_level = 8;
    repeated NodeState state_list = 9;
    bool deleting = 10;
    repeated uint64 cntlr_id_list = 11;
    repeated uint64 slice_id_list = 12;
    repeated string td_name_list = 13;
    repeated string nqn_list = 14;
    repeated string clone_name_list = 15;
    repeated string xfer_name_list = 16;
    repeated string migr_name_list = 17;
}

// {dnv_prefix} cntlr {cluster_id} {sp_id} {cntlr_id}
message Cntlr {
    string cn_addr_addr = 1;
	NvmeTrConf nvme_tr_conf = 2;
    uint32 cntlid_slot = 3;
    bool primary = 4;
	uint32 cntlr_idx = 5;
}

// {dnv_prefix} slice {cluster_id} {sp_id} {slice_id}
message Slice {
    uint32 slice_idx = 1;
    repeated Group meta_grp_list = 2;
    repeated Group data_grp_list = 3;
}

// {dnv_prefix} thin_device {cluster_id} {sp_id} {td_name}
message ThinDevice {
    uint64 td_id = 1;
    uint32 dev_id = 2;
    uint32 ori_id = 3;
    uint64 size = 4;
}

// {dnv_prefix} subsystem {cluster_id} {sp_id} {nqn}
message Subsystem {
    uint64 ss_id = 1;
    string serial = 2;
    string model = 3;
    repeated Namespace ns_list = 4;
    repeated string allowed_hosts = 5;
}

// {dnv_prefix} clone {cluster_id} {sp_id} {clone_name}
message Clone {
    uint64 clone_id = 1;
    repeated NvmeTrConf src_tr_conf_list = 2;
    string src_nqn = 3;
    uint32 src_ns_idx = 4;
    uint64 dst_td_id = 5;
    DmCloneConf dm_clone_conf = 6;
    bytes bitmap = 7;
    bool auto_resume = 8;
}

// {dnv_prefix} transfer {cluster_id} {sp_id} {xfer_name}
message Transfer {
    uint64 xfer_id = 1;
    string ori_nqn = 2;
    uint32 ori_ns_idx = 3;
    repeated string allowed_hosts = 4;
    bool auto_suspend = 5;
}

// {dnv_prefix} migration {cluster_id} {sp_id} {migr_name}
message Migration {
    uint64 migr_id = 1;
    uint64 src_side_id = 2;
    uint64 dst_side_id = 3;
    DmCloneConf dm_clone_conf = 4;
    bytes bitmap = 5;
}

// {dnv_prefix} sp_id_to_name {cluster_id} {sp_id}
message SpName {
    string sp_name = 1;
}

message CreateClusterRequest {
    string cluster_name = 1;
    QosRatio qos_ratio = 2;
    BdevConf bdev_conf = 3;
    DnBinConf dn_bin_conf = 4;
    AllocConf alloc_conf = 5;
}

message CreateClusterReply {
    uint64 cluster_id = 1;
}

message DeleteClusterRequest {
    string cluster_name = 1;
}

message DeleteClusterReply {
    uint64 cluser_id = 1;
}

message GetClusterRequest {
    string cluster_name = 1;
}

message GetClusterReply {
    string cluster_name = 1;
    uint64 cluster_id = 2;
    ClusterConf cluster_conf = 3;
    DnGlobal dn_global = 4;
    CnGlobal cn_global = 5;
    SpGlobal sp_global = 6;
}

message ListClustersRequest {
    uint32 count = 1;
    string page_token = 2;
}

message ListClustersReply {
    repeated string cluster_name = 1;
}

message CreateDiskNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
    NvmeTrConf nvme_tr_conf = 3;
    string location = 4;
    bool enabled = 5;
}

message CreateDiskNodeReply {
    uint64 dn_id = 1;
}

message DeleteDiskNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
    DnRev dn_rev = 3;
}

message DeleteDiskNodeReply {
    uint64 dn_id = 1;
}

message GetDiskNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
}

message GetDiskNodeReply {
    string addr_port = 1;
    DnConf dn_conf = 2;
    DnRev dn_rev = 3;
}

message ListDiskNodesRequest {
    string cluster_name = 1;
    uint32 count = 2;
    string page_token = 3;
}

message ListDiskNodesReply {
    repeated string addr_port = 1;
    string page_token = 2;
}

message SetDiskNodeStateRequest {
    string cluster_name = 1;
    string addr_port = 2;
    DnRev dn_rev = 3;
    uint32 idx = 4;
}

message SetDiskNodeStateReply {
    uint32 state = 1;
}

message ClearDiskNodeStateRequest {
    string cluster_name = 1;
    string addr_port = 2;
    DnRev dn_rev = 3;
    uint32 idx = 4;
}

message ClearDiskNodeStateReply {
    uint32 state = 1;
}

message InspectDiskNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
}

message InspectDiskNodeReply {
    LiveInfo live_info = 1;
}

message CreateControllerNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
    NvmeTrConf nvme_tr_conf = 3;
    string location = 4;
    bool enabled = 5;
}

message CreateControllerNodeReply {
    uint64 cn_id = 1;
}

message DeleteControllerNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
    CnRev cn_rev = 3;
}

message DeleteControllerNodeReply {
    uint64 cn_id = 1;
}

message GetControllerNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
}

message GetControllerNodeReply {
    string addr_port = 1;
    CnConf cn_conf = 2;
    CnRev cn_rev = 3;
}

message ListControllerNodesRequest {
    string cluster_name = 1;
    uint32 count = 2;
    string page_token = 3;
}

message ListControllerNodesReply {
    repeated string addr_port = 1;
    string page_token = 2;
}

message SetControllerNodeStateRequest {
    string cluster_name = 1;
    string addr_port = 2;
    CnRev cn_rev = 3;
    uint32 idx = 4;
}

message SetControllerNodeStateReply {
    uint32 state = 1;
}

message ClearControllerNodeStateRequest {
    string cluster_name = 1;
    string addr_port = 2;
    CnRev cn_rev = 3;
    uint32 idx = 4;
}

message ClearControllerNodeStateReply {
    uint32 state = 1;
}

message InspectControllerNodeRequest {
    string cluster_name = 1;
    string addr_port = 2;
}

message InspectControllerNodeReply {
    LiveInfo live_info = 1;
}

message CreateStoragePoolRequest {
    string cluster_name = 1;
    string sp_name = 2;
    BdevConf bdev_conf = 3;
	repeated uint32 cntlid_slot_list = 4;
    uint32 cntlr_cnt = 5;
    uint32 slice_cnt = 6;
    uint64 init_ext_cnt = 7;
    NodeSelector cn_selector = 8;
    NodeSelector dn_selector = 9;
}

message CreateStoragePoolReply {
    uint64 sp_id = 1;
}

message DeleteStoragePoolRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
}

message DeleteStoragePoolReply {
    uint64 sp_id = 1;
}

message GetStoragePoolRequest {
    string cluster_name = 1;
    string sp_name = 2;
}

message GetStoragePoolReply {
    string sp_name = 1;
    SpConf sp_conf = 2;
    SpRev sp_rev = 3;
    repeated Cntlr cntlr_list = 4;
    repeated Slice slice_list = 5;
}

message ListStoragePoolsRequest {
    string cluster_name = 1;
    uint32 count = 2;
    string page_token = 3;
}

message ListStoragePoolsReply {
    repeated string sp_name = 1;
    string page_token = 2;
}

message UpdateStoragePoolCntlidSlotListRequest {
    string cluster_name = 1;
	string sp_name = 2;
    SpRev sp_rev = 3;
	repeated uint32 cntlid_slot_list = 4;
}

message UpdateStoragePoolCntlidSlotListReply {
    uint64 sp_id = 1;
}

message UpdateStoragePoolLevelRequest {
    string cluster_name = 1;
	string sp_name = 2;
    SpRev sp_rev = 3;
	SpLevel sp_level = 4;
}

message UpdateStoragePoolLevelReply {
    uint64 sp_id = 1;
}

message SetStoragePoolStateRequest {
    string cluster_name = 1;
	string sp_name = 2;
    SpRev sp_rev = 3;
	uint32 state_idx = 4;
}

message SetStoragePoolStateReply {
    uint64 sp_id = 1;
}

message ClearStoragePoolStateRequest {
    string cluster_name = 1;
	string sp_name = 2;
    SpRev sp_rev = 3;
	uint32 state_idx = 4;
}

message ClearStoragePoolStateReply {
    uint64 sp_id = 1;
}

message FindStoragePoolNamesRequest {
    string cluster_name = 1;
    repeated uint64 sp_id_list = 2;
}

message FindStoragePoolNamesReply {
    map<uint64, string> sp_id_to_name = 1;
}

message GrowSliceRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    uint64 slice_id = 4;
    uint64 ext_cnt = 5;
    bool is_meta = 6;
    NodeSelector dn_selector = 7;
}

message GrowSliceReply {
    uint64 slice_id = 1;
    uint64 grp_id = 2;
}

message CreateCntlrRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    uint32 cntlid_slot = 4;
    NodeSelector cn_selector = 5;
}

message CreateCntlrReply {
    uint64 cntlr_id = 1;
}

message DeleteCntlrRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    uint64 cntlr_id = 4;
}

message DeleteCntlrReply {
    uint64 cntlr_id = 1;
}

message UpdateCntlrEnabledRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    uint64 cntlr_id = 4;
    bool enabled = 5;
}

message UpdateCntlrEnabledReply {
    uint64 cntlr_id = 1;
	bool enabled = 2;
}

message InspectCntlrRequest {
    string cluster_name = 1;
    string sp_name = 2;
    uint64 cntlr_id = 3;
}

message InspectCntlrReply {
    LiveInfo live_info = 1;
}

message InspectSideRequest {
    string cluster_name = 1;
    string sp_name = 2;
    uint64 side_id = 3;
}

message InspectSideReply {
    LiveInfo live_info = 1;
}

message CreateThinDeviceRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string td_name = 4;
    uint32 ori_name = 5;
    uint64 size = 6;
}

message CreateThinDeviceReply {
    uint64 td_id = 1;
	uint32 dev_id = 2;
}

message DeleteThinDeviceRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string td_name = 4;
}

message DeleteThinDeviceReply {
    uint64 td_id = 1;
}

message ListThinDevicesRequest {
    string cluster_name = 1;
    string sp_name = 2;
}

message ListThinDevicesReply {
    map<string, ThinDevice> name_to_td = 1;
}

message CreateSubsystemRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string nqn = 4;
    repeated string allowed_hosts = 5;
}

message CreateSubsystemReply {
    uint64 ss_id = 1;
}

message DeleteSubsystemRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string nqn = 4;
}

message DeleteSubsystemReply {
    uint64 ss_id = 1;
}

message ListSubsystemsRequest {
    string cluster_name = 1;
    string sp_name = 2;
}

message ListSubsystemsReply {
    map<string, Subsystem> nqn_to_subsystem = 1;
}

message UpdateSubsystemHostsRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string nqn = 4;
    repeated string allowed_hosts = 5;
}

message UpdateSubsystemHostsReply {
    uint64 ss_id = 1;
}

message CreateNamespaceRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string nqn = 4;
    uint32 ns_idx = 5;
    string td_name = 6;
}

message CreateNamespaceReply {
    uint64 ns_id = 1;
}

message DeleteNamespaceRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string nqn = 4;
    uint32 ns_idx = 5;
}

message DeleteNamespaceReply {
    uint64 ns_id = 1;
}

message UpdateNamespaceDevRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string nqn = 4;
    uint32 ns_idx = 5;
    string td_name = 6;
}

message UpdateNamespaceDevReply {
    uint64 ns_id = 1;
}

message UpdateNamespaceSuspendedRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string nqn = 4;
    uint32 ns_idx = 5;
    bool suspended = 6;
}

message UpdateNamespaceSuspendedReply {
    uint64 ns_id = 1;
}

message CreateCloneRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string  clone_name = 4;
    repeated NvmeTrConf src_tr_conf = 5;
    string src_nqn = 6;
    uint32 src_ns_idx = 7;
    string dst_td_name = 8;
    DmCloneConf dm_clone_conf = 9;
    bytes bitmap = 10;
    bool auto_resume = 11;
}

message CreateCloneReply {
    uint64 clone_id = 1;
}

message DeleteCloneRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string  clone_name = 4;
    bool force = 5;
}

message DeleteCloneReply {
    uint64 clone_id = 1;
}

message GetCloneRequest {
    string cluster_name = 1;
    string sp_name = 2;
    string clone_name = 3;
}

message GetCloneReply {
    Clone clone = 1;
}

message UpdateCloneTrConfRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string  clone_name = 4;
    repeated NvmeTrConf src_tr_conf = 5;
}

message UpdateCloneTrConfReply {
    uint64 clone_id = 1;
}

message UpdateCloneBitmapRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string clone_name = 4;
    bytes bitmap = 5;
}

message UpdateCloneBitmapReply {
    uint64 clone_id = 1;
}

message CreateTransferRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string xfer_name = 4;
    string ori_nqn = 5;
    uint32 ori_ns_idx = 6;
    repeated string allowed_hosts = 7;
    bool auto_suspend = 8;
}

message CreateTransferReply {
    uint64 xfer_id = 1;
}

message DeleteTransferRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string xfer_name = 4;
    bool force = 5;
}

message DeleteTransferReply {
    uint64 xfer_id = 1;
}

message GetTransferRequest {
    string cluster_name = 1;
    string sp_name = 2;
    string xfer_name = 3;
}

message GetTransferReply {
    Transfer xfer = 1;
}

message UpdateTransferHostsRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string xfer_name = 4;
    repeated string allowed_hosts = 5;
}

message UpdateTransferHostsReply {
    uint64 xfer_id = 1;
}

message CreateMigrationRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string migr_name = 4;
    uint64 src_side_id = 5;
	NodeSelector dn_selector = 6;
    DmCloneConf dm_clone_conf = 7;
    bytes bitmap = 8;
}

message CreateMigrationReply {
    uint64 migr_id = 1;
}

message FinishMigrationRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string migr_name = 4;
    bool force = 5;
}

message FinishMigrationReply {
    uint64 migr_id = 1;
}

message CancelMigrationRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string migr_name = 4;
}

message CancelMigrationReply {
    uint64 migr_id = 1;
}

message GetMigrationRequest {
    string cluster_name = 1;
    string sp_name = 2;
    string migr_name = 3;
}

message GetMigrationReply {
    Migration migr = 1;
}

message UpdateMigrationBitmapRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string migr_name = 4;
    bytes bitmap = 5;
}

message UpdateMigrationBitmapReply {
    uint64 migr_id = 1;
}

message CreateSpareLegRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string grp_id = 4;
	NodeSelector dn_selector = 5;
}

message CreateSpareLegReply {
    uint64 leg_id = 1;
}

message DeleteSpareLegRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    string grp_id = 4;
}

message DeleteSpareLegReply {
    uint64 leg_id = 1;
}

message SwitchSpareLegRequest {
    string cluster_name = 1;
    string sp_name = 2;
    SpRev sp_rev = 3;
    uint64 grp_id = 4;
    uint64 spare_leg_id = 5;
    uint64 target_leg_id = 6;
}

message SwitchSpareLegReply {
    uint64 curr_active_leg_id = 1;
	uint64 curr_spare_leg_id = 2;
}

message GetThinDeviceBitmapRequest {
    string cluster_name = 1;
    string sp_name = 2;
    string td_name = 3;
}

message GetThinDeviceBitmapReply {
    uint64 region_size = 1;
    bytes bitmap = 2;
}

message GetLegBitmapRequest {
    string cluster_name = 1;
    string sp_name = 2;
    uint64 leg_id = 3;
}

message GetLegBitmapReply {
    uint64 region_size = 1;
    bytes bitmap = 2;
}

message GetTransferBitmapRequest {
    string cluster_name = 1;
    string sp_name = 2;
    uint64 leg_id = 3;
}

message GetTransferBitmapReply {
    uint64 region_size = 1;
    bytes bitmap = 2;
}

service Gateway {
    rpc CreateCluster(CreateClusterRequest) returns(CreateClusterReply) {}
    rpc DeleteCluster(DeleteClusterRequest) returns(DeleteClusterReply) {}
    rpc GetCluster(GetClusterRequest) returns(GetClusterReply) {}
    rpc ListClusters(ListClustersRequest) returns(ListClustersReply) {}

    rpc CreateDiskNode(CreateDiskNodeRequest) returns(CreateDiskNodeReply) {}
    rpc DeleteDiskNode(DeleteDiskNodeRequest) returns(DeleteDiskNodeReply) {}
    rpc GetDiskNode(GetDiskNodeRequest) returns(GetDiskNodeReply) {}
    rpc ListDiskNodes(ListDiskNodesRequest) returns(ListDiskNodesReply) {}
    rpc SetDiskNodeState(SetDiskNodeStateRequest) returns(SetDiskNodeStateReply) {}
    rpc ClearDiskNodeState(ClearDiskNodeStateRequest) returns(ClearDiskNodeStateReply) {}
    rpc InspectDiskNode(InspectDiskNodeRequest) returns(InspectDiskNodeReply) {}

    rpc CreateControllerNode(CreateControllerNodeRequest) returns(CreateControllerNodeReply) {}
    rpc DeleteControllerNode(DeleteControllerNodeRequest) returns(DeleteControllerNodeReply) {}
    rpc GetControllerNode(GetControllerNodeRequest) returns(GetControllerNodeReply) {}
    rpc ListControllerNodes(ListControllerNodesRequest) returns(ListControllerNodesReply) {}
    rpc SetControllerNodeState(SetControllerNodeStateRequest) returns(SetControllerNodeStateReply) {}
    rpc ClearControllerNodeState(ClearControllerNodeStateRequest) returns(ClearControllerNodeStateReply) {}
    rpc InspectControllerNode(InspectControllerNodeRequest) returns(InspectControllerNodeReply) {}

    rpc CreateStoragePool(CreateStoragePoolRequest) returns(CreateStoragePoolReply) {}
    rpc DeleteStoragePool(DeleteStoragePoolRequest) returns(DeleteStoragePoolReply) {}
    rpc GetStoragePool(GetStoragePoolRequest) returns(GetStoragePoolReply) {}
    rpc ListStoragePools(ListStoragePoolsRequest) returns(ListStoragePoolsReply) {}
	rpc UpdateStoragePoolCntlidSlotList(UpdateStoragePoolCntlidSlotListRequest) returns(UpdateStoragePoolCntlidSlotListReply) {}
	rpc UpdateStoragePoolLevel(UpdateStoragePoolLevelRequest) returns(UpdateStoragePoolLevelReply) {}
    rpc SetStoragePoolState(SetStoragePoolStateRequest) returns(SetStoragePoolStateReply) {}
    rpc ClearStoragePoolState(ClearStoragePoolStateRequest) returns(ClearStoragePoolStateReply) {}
    rpc FindStoragePoolName(FindStoragePoolNamesRequest) returns(FindStoragePoolNamesReply) {}

    rpc GrowSlice(GrowSliceRequest) returns(GrowSliceReply) {}

    rpc CreateCntlr(CreateCntlrRequest) returns(CreateCntlrReply) {}
    rpc DeleteCntlr(DeleteCntlrRequest) returns(DeleteCntlrReply) {}
    rpc UpdateCntlrEnabled(UpdateCntlrEnabledRequest) returns(UpdateCntlrEnabledReply) {}

    rpc InspectCntlr(InspectCntlrRequest) returns(InspectCntlrReply) {}
    rpc InspectSide(InspectSideRequest) returns(InspectSideReply) {}

    rpc CreateThinDevice(CreateThinDeviceRequest) returns(CreateThinDeviceReply) {}
    rpc DeleteThinDevice(DeleteThinDeviceRequest) returns(DeleteThinDeviceReply) {}
    rpc ListThinDevices(ListThinDevicesRequest) returns(ListThinDevicesReply) {}

    rpc CreateSubsystem(CreateSubsystemRequest) returns(CreateSubsystemReply) {}
    rpc DeleteSubsystem(DeleteSubsystemRequest) returns(DeleteSubsystemReply) {}
    rpc ListSubsystems(ListSubsystemsRequest) returns(ListSubsystemsReply) {}
    rpc UpdateSubsystemHosts(UpdateSubsystemHostsRequest) returns(UpdateSubsystemHostsReply) {}

    rpc CreateNamespace(CreateNamespaceRequest) returns(CreateNamespaceReply) {}
    rpc DeleteNamespace(DeleteNamespaceRequest) returns(DeleteNamespaceReply) {}
    rpc UpdateNamespaceDev(UpdateNamespaceDevRequest) returns(UpdateNamespaceDevReply) {}
    rpc UpdatenamespaceSuspended(UpdateNamespaceSuspendedRequest) returns(UpdateNamespaceSuspendedReply) {}

    rpc CreateClone(CreateCloneRequest) returns(CreateCloneReply) {}
    rpc DeleteClone(DeleteCloneRequest) returns(DeleteCloneReply) {}
    rpc GetClone(GetCloneRequest) returns(GetCloneReply) {}
    rpc UpdateCloneTrConf(UpdateCloneTrConfRequest) returns(UpdateCloneTrConfReply) {}
    rpc UpdateCloneBitmap(UpdateCloneBitmapRequest) returns(UpdateCloneBitmapReply) {}

    rpc CreateTransfer(CreateTransferRequest) returns(CreateTransferReply) {}
    rpc DeleteTransfer(DeleteTransferRequest) returns(DeleteTransferReply) {}
    rpc GetTransfer(GetTransferRequest) returns(GetTransferReply) {}
    rpc UpdateTransferHosts(UpdateTransferHostsRequest) returns(UpdateTransferHostsReply) {}

    rpc CreateMigration(CreateMigrationRequest) returns(CreateMigrationReply) {}
    rpc FinishMigration(FinishMigrationRequest) returns(FinishMigrationReply) {}
    rpc CancelMigration(CancelMigrationRequest) returns(CancelMigrationReply) {}
    rpc GetMigration(GetMigrationRequest) returns(GetMigrationReply) {}
    rpc UpdateMigrationBitmap(UpdateMigrationBitmapRequest) returns(UpdateMigrationBitmapReply) {}

    rpc CreateSpareLeg(CreateSpareLegRequest) returns(CreateSpareLegReply) {}
    rpc DeleteSpareLeg(DeleteSpareLegRequest) returns(DeleteSpareLegReply) {}
    rpc SwitchSpareLeg(SwitchSpareLegRequest) returns(SwitchSpareLegReply) {}

    rpc GetThinDeviceBitmap(GetThinDeviceBitmapRequest) returns(GetThinDeviceBitmapReply) {}
    rpc GetLegBitmap(GetLegBitmapRequest) returns(GetLegBitmapReply) {}
    rpc GetTransferBitmap(GetTransferBitmapRequest) returns(GetTransferBitmapReply) {}
}

message GetDnSizeRequest {
    uint64 cluster_id = 1;
    uint64 dn_id = 2;
}

message GetDnSizeReply {
    uint64 size = 1;
}

message SyncupDnRequest {
    uint64 cluster_id = 1;
    uint64 dn_id = 2;
    uint64 revision = 3;
	ClusterConf cluster_conf = 4;
    bool partial = 5;
    repeated SidePointer side_pointer_list = 6;
}

message SyncupDnReply {
    AgentReply agent_reply = 1;
    LiveInfo live_info = 2;
}

message SyncupSideRequest {
    uint64 cluster_id = 1;
    uint64 dn_id = 2;
    SidePointer side_poiner = 3;
    uint64 revision = 4;
	bool partial = 5;
    uint64 ext_cnt = 6;
	uint64 primary_cn_id = 7;
	uint32 primary_idx = 8;
	map<uint64, uint32> standby_id_to_idx = 9;
    Side src_side = 10;
}

message SyncupSideReply {
    AgentReply agent_reply = 1;
    LiveInfo live_info = 2;
}

message GetDnInfoRequest {
    uint64 cluster_id = 1;
    uint64 dn_id = 2;
}

message GetDnInfoReply {
    AgentReply agent_reply = 1;
    LiveInfo live_info = 2;
}

message GetSideInfoRequest {
    uint64 cluster_id = 1;
    uint64 dn_id = 2;
    SidePointer side_pointer = 3;
}

message GetSideInfoReply {
    AgentReply agent_reply = 1;
    LiveInfo live_info = 2;
}

service DiskNodeAgent {
    rpc GetDnSize(GetDnSizeRequest) returns(GetDnSizeReply) {}
    rpc SyncupDn(stream SyncupDnRequest) returns(stream SyncupDnReply) {}
    rpc SyncupSide(stream SyncupSideRequest) returns(stream SyncupSideReply) {}
    rpc GetDnInfo(GetDnInfoRequest) returns(GetDnInfoReply) {}
    rpc GetSpLdInfo(GetSideInfoRequest) returns(GetSideInfoReply) {}
}

message GetCnSizeRequest {
    uint64 cluster_id = 1;
    uint64 cn_id = 2;
}

message GetCnSizeReply {
    uint64 size = 1;
}

message SyncupCnRequest {
    uint64 cluster_id = 1;
    uint64 cn_id = 2;
    uint64 revision = 3;
	ClusterConf cluster_conf = 4;
	bool partial = 5;
    repeated CntlrPointer cntlr_pointer_list = 6;
}

message SyncupCnReply {
    AgentReply agent_reply =  1;
    LiveInfo live_info = 2;
}

message SyncupCntlrRequest {
    uint64 cluster_id = 1;
    uint64 cn_id = 2;
    uint64 sp_id = 3;
    uint64 cntlr_id = 4;
    uint64 revision = 5;
	bool partial = 6;
    BdevConf bdev_conf = 7;
    Cntlr cntlr = 8;
	map<string, Slice> id_to_slice = 9;
    repeated ThinDevice td_list = 10;
	map<string, Subsystem> nqn_to_subsystem = 11;
    repeated Clone clone_list = 12;
    repeated Transfer xfer_list = 13;
    repeated Migration migr_list = 14;
}

message SyncupCntlrReply {
    AgentReply agent_reply = 1;
    LiveInfo live_info = 2;
}

message GetCnInfoRequest {
    uint64 cluster_id = 1;
    uint64 cn_id = 2;
}

message GetCnInfoReply {
    AgentReply agent_reply = 1;
    LiveInfo live_info = 2;
}

message GetCntlrInfoRequest {
    uint64 cluster_id = 1;
    uint64 cn_id = 2;
    uint64 sp_id = 3;
    uint64 cntlr_id = 4;
}

message GetCntlrInfoReply {
    AgentReply agent_reply = 1;
    LiveInfo live_info = 2;
}

service ControllerNodeAgent {
    rpc GetCnSize(GetCnSizeRequest) returns(GetCnSizeReply) {}
    rpc SyncupCn(stream SyncupCnRequest) returns(stream SyncupCnReply) {}
    rpc SyncupCntlr(stream SyncupCntlrRequest) returns(stream SyncupCntlrReply) {}
    rpc GetCnInfo(GetCnInfoRequest) returns(GetCnInfoReply) {}
    rpc GetCntlrInfo(GetCntlrInfoRequest) returns(GetCntlrInfoReply) {}
}